### ISSUE TITLE
Item model lighting issue when this mod is run with shaders

### ISSUE THREAD

**Issue by StockiesLad** [RaphiMC/ImmediatelyFast#16]
without:
![image](https://user-images.githubusercontent.com/60066663/210208627-d680a645-1e80-4229-b76b-91975679778e.png)

with:
![image](https://user-images.githubusercontent.com/60066663/210208660-f2da1e9f-d4da-45cc-be28-8d908c400c76.png)

**Comment by StockiesLad** [comment]
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/10330597/latest.log)

**Comment by adueppen** [comment]
I've observed this behavior too, any chance it might have something to do with https://github.com/IrisShaders/Iris/issues/1779?

**Comment by RaphiMC** [comment]
Looks like pretty much that issue. I already reported it on their discord as well, but no reponse yet

**Comment by MCSmallCai** [comment]
![2023-01-07_14 40 14](https://user-images.githubusercontent.com/121654450/211135475-34b52348-07d1-49c2-bbe0-d6e118b53afb.png)
![2023-01-07_14 40 25](https://user-images.githubusercontent.com/121654450/211135479-4468bc43-3995-496d-805a-5fbbf902af05.png)
Iris-1.5.0+BSL-v8.1.02.2 also have this problem

**Comment by RaphiMC** [comment]
I sadly can't do much on my side to fix that. The issue has been reported to Iris on github and I reported it on their discord, but I haven't had a response yet on either

**Comment by RaphiMC** [comment]
This issue seems to be fixed (probably by my Z sorting recode) in ImmediatelyFast 1.1.6. Please retest using the latest version of ImmediatelyFast

**Comment by StockiesLad** [comment]
yep alright.

**Comment by StockiesLad** [comment]
it works. Needs more testing to ensure it works everywhere. But we're on to a good start

**Comment by RaphiMC** [comment]
I will close the issue for now. Should further problems arise, I can reopen it again

**Comment by StockiesLad** [comment]
Sounds good!

**Comment by StockiesLad** [comment]
Yep, it works for iris 1.5 and in my 300 mod-large modpack. I think this issue is resolved entirely.

**Comment by MCSmallCai** [comment]
I updated InstantFast 1.1.6, but the above situation still appears

**Comment by RaphiMC** [comment]
Do you have any other mods installed? If no, send the shaderpack

**Comment by MCSmallCai** [comment]
There are no other mods. My mod folder is iris-1.5.0 ImmediatelyFast-1.1.6 sodium-0.4.4 fabric-api-0.72.0
shaderpack is BSL_v8.1.02.2

**Comment by RaphiMC** [comment]
Can you please upload the zip file of the shaderpack

**Comment by MCSmallCai** [comment]
[Uploading BSL_v8.1.02.2.zip…]()

**Comment by MCSmallCai** [comment]
And my profile
[BSL_v8.1.02.2.zip.txt](https://github.com/RaphiMC/ImmediatelyFast/files/10366363/BSL_v8.1.02.2.zip.txt)

**Comment by MCSmallCai** [comment]
[BSL_v8.1.02.2.zip.txt](https://github.com/RaphiMC/ImmediatelyFast/files/10366365/BSL_v8.1.02.2.zip.txt)

**Comment by MCSmallCai** [comment]
[Uploading BSL_v8.1.02.2.zip…]()

**Comment by RaphiMC** [comment]
What minecraft version are you using?

**Comment by MCSmallCai** [comment]
1.19.2

**Comment by RaphiMC** [comment]
The lighting looks normal for me, can you send a screenshot of the issue? (Compared with and without IF)

**Comment by RaphiMC** [comment]
And upload a game log please

**Comment by MCSmallCai** [comment]
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/10366408/latest.log)
![2023-01-07_21 49 24](https://user-images.githubusercontent.com/121654450/211154087-30171343-8def-4890-9bf2-78ce3372cb61.png)![2023-01-07_21 49 31](https://user-images.githubusercontent.com/121654450/211154091-9cab04ec-72e2-4eba-8cc3-e49a9179b080.png)

**Comment by RaphiMC** [comment]
Can you update your mods. Some of them are outdated (like sodium for example)

**Comment by RaphiMC** [comment]
Nvm, sodium 0.4.4 is the latest for 1.19.2. Can you maybe try if the issue also occurs in 1.19.3? I still can't reproduce it

**Comment by RaphiMC** [comment]
Managed to reproduce it with enchanted items

**Comment by MCSmallCai** [comment]
Okay, I'll try

**Comment by RaphiMC** [comment]
I already reproduced it. You don't have to try it anymore

**Comment by MCSmallCai** [comment]
This also happens to me on 1.19.3

**Comment by adueppen** [comment]
With version 1.1.6 of this mod and Iris 1.5.0 on 1.19.2 (and [Complementary Reimagined r1.4](https://www.curseforge.com/minecraft/customization/complementary-reimagined/files/4249677)) I'm noticing this bug to be mostly fixed, but with the exception of items with an enchantment glint while in-game (not in inventory).
![Screenshot from 2023-01-15 10-17-32](https://user-images.githubusercontent.com/6982070/212552846-88d9fbac-d0e9-43e0-8274-e59095630612.png)
![Screenshot from 2023-01-15 10-16-36](https://user-images.githubusercontent.com/6982070/212552847-96e2455c-f19f-4b46-b92b-a124f453cc80.png)

**Comment by StockiesLad** [comment]
it makes gold look like wood lol.

**Comment by RaphiMC** [comment]
In ImmediatelyFast 1.1.8 item batching will be disabled by default. This will fix the issue

**Comment by RaphiMC** [comment]
ImmediatelyFast 1.1.9 properly fixes this issue now. Item Batching will stay disabled by default due to it still breaking some mods/resource packs, but it can now be safely reenabled even with Iris installed.
