### ISSUE TITLE
Mod breaks text and GUI rendering on servers with custom resource pack

### ISSUE THREAD

**Issue by Andre601** [RaphiMC/ImmediatelyFast#29]
Encountered these issues on the Server Origin Realms, where text and GUI elements (I assume the GUI element also was text) were broken while this mod is active.

With mod active:
![bossbar](https://user-images.githubusercontent.com/11576465/213582351-bc005d71-b57d-45eb-992c-492739c2420d.png)

![gui](https://user-images.githubusercontent.com/11576465/213582582-077a9f5f-8d54-4d9f-a52f-25451ffdf6b1.png)

Without the mod:
![bossbar](https://user-images.githubusercontent.com/11576465/213582755-ec20f5d1-71a8-42b3-9c3b-c4d4ad198660.png)

![gui](https://user-images.githubusercontent.com/11576465/213582810-588c70a8-9f0e-46da-9b5f-52cc5e80a6db.png)

The server is utilizing a custom resource pack, which also alters some vanilla core shaders. It does not use any kind of server mods. Only plugins.

**Comment by RaphiMC** [comment]
This has been fixed in ImmediatelyFast 1.1.7. Please update

**Comment by gousisme** [comment]
Still doesn't fix the text in 1.1.7 tho, some texts in the GUI are still getting this bug
![image](https://user-images.githubusercontent.com/77152530/213598272-2f2d37c5-4210-4a6e-b644-7b038f21f2bf.png)

**Comment by gousisme** [comment]
Just tested some options in the config, turns out it's "hud_batching", this option will break the trident's texture only when it's on the hot bar
with "hud_batching": false
![image](https://user-images.githubusercontent.com/77152530/213744754-299cbd35-8016-4635-a87b-3358110a22f3.png)
![image](https://user-images.githubusercontent.com/77152530/213746377-8fc910b1-9129-44f8-ade2-0f56312b0110.png)
with "hud_batching": true
![image](https://user-images.githubusercontent.com/77152530/213746118-e2f4803c-b040-4536-b179-235253d927fd.png)
![image](https://user-images.githubusercontent.com/77152530/213746278-3aa472bb-810f-4bcf-ac60-ddd0ab0fc5b5.png)

Edit: It's only happening on the server since they are using leather horse armor for the trident.

**Comment by RaphiMC** [comment]
In ImmediatelyFast 1.1.8 item batching will be disabled by default. This will fix the issue
