### ISSUE TITLE
Latest update visual bug with durability indicator

### ISSUE THREAD

**Issue by polykatt** [RaphiMC/ImmediatelyFast#316]
I just updated ImmediatelyFast to 1.3.6 on Neoforge 1,21,1 there is a visual bug with the durability bar for items on the hotbar. It looks like the durability bar is displayed behind the item texture rather than over it as it normally is. Going back to 1.3.5 doesn't have this issue

![Image](https://github.com/user-attachments/assets/5dee94aa-5ede-4a1a-8640-d9dcfad41a55)

**Comment by SkyRunner55** [comment]
i can confirm that append to me also, it broke [jade mod](https://www.curseforge.com/minecraft/mc-mods/jade) block display at the top

![Image](https://github.com/user-attachments/assets/53652517-1539-4148-ad11-70d79d75607e)

**Comment by XNFu233233233** [comment]
> 我可以确认附加到我身上，它破坏了顶部的[玉石模块显示](https://www.curseforge.com/minecraft/mc-mods/jade)
> 
> ![Image](https://github.com/user-attachments/assets/53652517-1539-4148-ad11-70d79d75607e)

I also had this problem, and jade was normal when I opened the chat bar

**Comment by SkyRunner55** [comment]
that odd x)

**Comment by Lucky-56** [comment]
you can edit the title @polykatt

**Comment by SkyRunner55** [comment]
> > 我可以确认附加到我身上，它破坏了顶部的[玉石模块显示](https://www.curseforge.com/minecraft/mc-mods/jade)
> 
> I also had this problem, and jade was normal when I opened the chat bar

also noticed the name of modded blocked showed up but not correctly, i guess fixing the vanilla thing will fix also

![Image](https://github.com/user-attachments/assets/642344f6-32d1-40b7-81de-304678a5346a)

**Comment by endavis** [comment]
+1 for this issue. 

Here are the images from 1.3.5 vs 1.3.6. Tooltips work in inventory for both versions. 1.3.6 does not render tool tips when looking at objects in the world.

![Image](https://github.com/user-attachments/assets/5c00510b-339b-44f6-affa-3dc9317faf2f)
![Image](https://github.com/user-attachments/assets/536036e9-1715-437c-b884-ca03a9586414)
![Image](https://github.com/user-attachments/assets/f3683908-7b6d-42ae-a787-2fd54651d0b9)

[immediately-fast-logs.zip](https://github.com/user-attachments/files/19094543/immediately-fast-logs.zip) This contains my logs for immediately fast 1.3.5 and 1.3.6

**Comment by RaphiMC** [comment]
I can confirm the issue and I am working on a fix

**Comment by RaphiMC** [comment]
The JourneyMap / Jade issue has been fixed: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/13686236624
Working on the durability bar issue now

**Comment by RaphiMC** [comment]
Fixed the item durability bar issue as well: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/13687258727

**Comment by RaphiMC** [comment]
Uploaded a new release (ImmediatelyFast 1.6.0) to CurseForge and Modrinth

**Comment by SkyRunner55** [comment]
the bug is back with the latest update but in another way (version 1.6.3)

![Image](https://github.com/user-attachments/assets/62352693-5f02-4c2c-9ed1-ecb4ac13076d)

**Comment by RaphiMC** [comment]
@SkyRunner55 I could not reproduce the issue with the 1.6.3 update:
![Image](https://github.com/user-attachments/assets/9ef4e7bd-d321-4d11-8d31-df2ba2035c15)

Please open a new issue with detailed steps to reproduce your issue because this issue was really about the item durability bar

**Comment by SkyRunner55** [comment]
> [@SkyRunner55](https://github.com/SkyRunner55) I could not reproduce the issue with the 1.6.3 update: ![Image](https://github.com/user-attachments/assets/9ef4e7bd-d321-4d11-8d31-df2ba2035c15)
> 
> Please open a new issue with detailed steps to reproduce your issue because this issue was really about the item durability bar

well its not appening anymore so, i'm not gonna reopen a issue, since its working
