### ISSUE TITLE
Oceanblock 2 FTB Ultimine Overlay

### ISSUE THREAD

**Issue by njasak** [RaphiMC/ImmediatelyFast#318]
For some reasonin Oceanblock latest update 1.4.0 they use v1.3.6 of your mod, and it interferes FTB Ultimine overlay that pops up, I switched to 1.3.5 and it fixes itself, Just informing you. I did see you updated to 1.6 and I don't know if it works , but the modpack is at 1.3.6

**Comment by RaphiMC** [comment]
Upload the game log and attach screenshots which show how it looks with ImmediatelyFast 1.3.6 and one with 1.3.5

**Comment by njasak** [comment]
ok Ill try but I got it from this post
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/7219 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/7233

**Comment by njasak** [comment]
7233 has a log in it

**Comment by RaphiMC** [comment]
I managed to reproduce the bug with ImmediatelyFast 1.3.6. The bug is already fixed in ImmediatelyFast 1.6.0.

**Comment by truehiddenevil** [comment]
Issue still occurs with 1.6.0. That is why I mentioned 1.3.5 working instead of upgrading to 1.6.0

**Comment by RaphiMC** [comment]
I wrongly assumed the minimap mod used was JourneyMap and thats why I thought the issue was fixed. Its broken with FTB Chunks minimap

**Comment by RaphiMC** [comment]
This issue is now actually fixed. Here is the dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/13743075814
