### ISSUE TITLE
Incompatibility with Equipment Compare

### ISSUE THREAD

**Issue by kapuchai** [RaphiMC/ImmediatelyFast#329]
There is an issue with Equipment Compare (https://modrinth.com/mod/equipment-compare) mod, when both mods are active comparison tooltip is blank (see screenshots). I tried disabling all options in IF's config but still having this issue. 

Fabric 1.21.1
ImmediatelyFast 1.6.1
Equipment Compare 1.3.12

![Image](https://github.com/user-attachments/assets/0bf7a7c7-28f6-4dc3-aabd-39354fae846c)
![Image](https://github.com/user-attachments/assets/13cb5cf8-b1ff-4f9d-8f85-cc382708a14a)

**Comment by RaphiMC** [comment]
I fixed the issue in this version: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/13875143298

**Comment by kapuchai** [comment]
Thank you!

**Comment by kapuchai** [comment]
It looks like this issue still persists in the latest version

**Comment by RaphiMC** [comment]
I retested it, and the issue does not persist:
![Image](https://github.com/user-attachments/assets/4266f9ad-d196-4451-9114-5ba804ce2c96)
Make sure to update the mods to at least this version:
* equipmentcompare 1.3.12
* fabric-api 0.115.2+1.21.1
* iceberg 1.2.9.2
* immediatelyfast 1.6.2+1.21.1

**Comment by kapuchai** [comment]
You're right, after retesting with just these 4 mods I can confirm that it works. But after adding Legendary Tooltips (https://modrinth.com/mod/legendary-tooltips) it breaks again :/
Sorry it seems like I forgot to mention I was using that too (actually forgot about it, just noticed that tooltips in your screenshot look different than in mine)
Oh well, I guess the issue needs to be renamed and reopened

**Comment by RaphiMC** [comment]
Please open a new issue for the legendary tooltips issue

**Comment by kapuchai** [comment]
Alright then, I will open new one
