### ISSUE TITLE
WebDisplays Incompatibility

### ISSUE THREAD

**Issue by Kewz4** [RaphiMC/ImmediatelyFast#394]
Hey there not really sure if this is at all possible. Is it possible for immediately fast to exclude some items? I am using webdisplays and the mod causes the item to render and have this flicker effect. If I remove IF the screen is now visible and no problems but I don't really want to miss on IF optimizations.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f34dcc82-dea8-4836-8527-192acf4698e4" />

Minecraft 1.20.1
Forge 47.4.0
ImmediatelyFast 1.5.1+1.20.4
WebDisplays  2.0.1-1.20.1

**Comment by Kewz4** [comment]
Hey there, was this fixed? Planning on building a mod pack and curious what's the current status. Thank you!

**Comment by RaphiMC** [comment]
I haven't specifically looked into this issue. There is a chance it got fixed by some unrelated fixes, if not, I can maybe fix it this month

**Comment by Kewz4** [comment]
It is still happening! 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/902e7691-dfd6-45d1-b176-17d83a540410" />

**Comment by RaphiMC** [comment]
I added this issue as a low priority issue to my todo list and might be able to work on it this month

**Comment by RaphiMC** [comment]
This issue has been fixed in the latest dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/19788359340
